branch-defaults:
  default:
    environment: Omega-env
environment-defaults:
  Omega-env:
    branch: null
    repository: null
global:
  application_name: omega
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
