[tool.black]
line-length = 88 # if not using Blackd Then set to 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    .git
  | .hg
  | .mypy_cache
  | .tox
  | ./Lib/*
  | _build
  | buck-out
  | build
  | .dist
)/
